// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEtXypnrPEinYH1urU2ogmtd_dzwJpfQo',
    appId: '1:778360596800:web:5b7f596c9b86fa878872a5',
    messagingSenderId: '778360596800',
    projectId: 'school-task-planner',
    authDomain: 'school-task-planner.firebaseapp.com',
    storageBucket: 'school-task-planner.firebasestorage.app',
    measurementId: 'G-8Q0MBEZC1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuciSCsQY1AnRgHR0teKXOZ97gE5czeEM',
    appId: '1:778360596800:android:fd06db90c704fb158872a5',
    messagingSenderId: '778360596800',
    projectId: 'school-task-planner',
    storageBucket: 'school-task-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4AMIH8ZVpJyJGRPCTrGwXxW15UZa8maM',
    appId: '1:778360596800:ios:c35fe44a42cd8e348872a5',
    messagingSenderId: '778360596800',
    projectId: 'school-task-planner',
    storageBucket: 'school-task-planner.firebasestorage.app',
    iosBundleId: 'com.example.schoolTaskPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4AMIH8ZVpJyJGRPCTrGwXxW15UZa8maM',
    appId: '1:778360596800:ios:c35fe44a42cd8e348872a5',
    messagingSenderId: '778360596800',
    projectId: 'school-task-planner',
    storageBucket: 'school-task-planner.firebasestorage.app',
    iosBundleId: 'com.example.schoolTaskPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEtXypnrPEinYH1urU2ogmtd_dzwJpfQo',
    appId: '1:778360596800:web:3145a74df42eeb998872a5',
    messagingSenderId: '778360596800',
    projectId: 'school-task-planner',
    authDomain: 'school-task-planner.firebaseapp.com',
    storageBucket: 'school-task-planner.firebasestorage.app',
    measurementId: 'G-VLFCT1XKD0',
  );

}